[mqtt]
address: PandaSensePro.local #Change to match the IP address of Panda Sense
port: 1883
client_id: moonraker
enable_tls: False
mqtt_protocol: v3.1
enable_moonraker_api: False
instance_name: my_printer

[sensor panda_sense_pro]
type: mqtt
name: Panda Sense Pro
qos: 0
state_topic: pandasensepro/sensor
state_response_template: |
  {% set resp = payload|fromjson %}
  {% set edata = resp["data"] %}
  {set_result("temperature", edata["temper"]|float)}
  {set_result("humidity", edata["humidity"])}
  {set_result("PM2_5", edata["pm2.5"])}
  {set_result("PM10", edata["pm10"])}
  {set_result("CO₂", edata["co2"])}
  {set_result("eTVOC", edata["etvoc"])}
  {set_result("CH₂O", edata["ch2o"])}
  {set_result("AQI", edata["aqi"])}

parameter_temperature:
  units=℃
parameter_humidity:
  units=%
parameter_PM2_5:
  units=µg/m³
parameter_PM10:
  units=µg/m³
parameter_CO₂:
  units=ppm
parameter_eTVOC:
  units=mg/m³
parameter_CH₂O:
  units=mg/m³
parameter_AQI:
  units=-
history_field_humidity_consumption:
  parameter=humidity
  desc=Printer humidity consumption
  strategy=average
  units=%
  init_tracker=true
  precision=6
  exclude_paused=false
  report_total=true
  report_maximum=true
